/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions, EventOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { Callback, TransactionObject, ContractEvent } from "./types";

export class DMDCertifiedUnique extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    supportsInterface(
      interfaceId: string | number[]
    ): TransactionObject<boolean>;

    getApproved(tokenId: number | string): TransactionObject<string>;

    ownerOf(tokenId: number | string): TransactionObject<string>;

    balanceOf(owner: string): TransactionObject<BN>;

    dataOwner(arg0: number | string): TransactionObject<string>;

    certifiers(
      arg0: number | string
    ): TransactionObject<{
      name: string;
      officialID: string;
      mainAddress: string;
      website: string;
      text: string;
      imageIPFSAddress: string;
      timestampAdded: BN;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: BN;
    }>;

    isApprovedForAll(
      owner: string,
      operator: string
    ): TransactionObject<boolean>;

    approve(to: string, tokenId: number | string): TransactionObject<void>;

    transferFrom(
      from: string,
      to: string,
      tokenId: number | string
    ): TransactionObject<void>;

    safeTransferFrom(
      from: string,
      to: string,
      tokenId: number | string
    ): TransactionObject<void>;

    renounceOwnership(): TransactionObject<void>;

    setApprovalForAll(to: string, approved: boolean): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    addCertifier(
      name: string | number[],
      officialID: string | number[],
      mainAddress: string,
      website: string,
      text: string,
      imageIPFSAddress: string | number[]
    ): TransactionObject<boolean>;

    addMotoModification(
      owner: string,
      predecessorID: number | string,
      certifierID: number | string,
      name: string | number[],
      nameBaseModel: string | number[],
      modificationPlainText: string,
      imageRessourcesIPFSAddress: string | number[],
      horsepower: number | string,
      weight: number | string,
      topSpeed: number | string,
      modificationDate: number | string,
      vintageGrade: number | string,
      techGrade: number | string
    ): TransactionObject<BN>;

    owner(): TransactionObject<string>;
    isOwner(): TransactionObject<boolean>;
  };
  events: {
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    Transfer: ContractEvent<{
      from: string;
      to: string;
      tokenId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    Approval: ContractEvent<{
      owner: string;
      approved: string;
      tokenId: BN;
      0: string;
      1: string;
      2: BN;
    }>;
    ApprovalForAll: ContractEvent<{
      owner: string;
      operator: string;
      approved: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
